### ISSUE TITLE
Styling issue on auth screen

### ISSUE THREAD

**Issue by SpaghettiC0des** [osaisacson/kretsloppan#45]
**Tasks**
- [ ] Remove large bottom padding pushes the screen
- [ ] Header title should be hidden
- [ ] Form container pushed upward
